# Generated by Django 2.2.16 on 2020-10-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hgfjhfh'),
    ]

    operations = [
        migrations.AddField(
            model_name='hgfjhfh',
            name='hgjfkhfghfgjfjh',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
